apiVersion: apps/v1
kind: Deployment
metadata:
  name: banane
  labels:
    app: banane
    name: banane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banane
  template:
    metadata:
      labels:
        app: banane
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - containerPort: 80
